---
title: "EDA_R_PROJECT"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidyr)
library(janitor)
library(DT)
library(kableExtra)
library(pROC)

```

```{r, data}
df_auto <- read.csv(paste0(getwd(),"/data_prep/car.csv"),
                    stringsAsFactors = TRUE)
#exposure adjusted glm..source(logit_exposure_adjusted.r)
#glm(survive ~ date, family=binomial(link=logitexp(exposure=df_auto$exposure)),
#    data=df_auto)
```

```{r}
df_auto <- df_auto[,-11]

df_auto$agecat <- as.factor(df_auto$agecat)


df_auto$clm <- as.factor(df_auto$clm)

df_auto$veh_band <- as.factor(cut(df_auto$veh_value,
                                  c(-1,2.5,5.0,7.5,10.0,12.5,100)))

levels(df_auto$veh_band) <- c("<=25","25-50","50-75","75-100","100-125",">125")

df_auto %>% 
  group_by(gender,clm) %>% 
  summarise(numclaims = sum(numclaims,na.rm = T),
            claimcst0 = sum(claimcst0,na.rm = T),
            .groups = "drop")
```


```{r, EDA}

summary(df_auto)

```

```{r, warning=FALSE}

#plot(restaurants[, -c(1, 6)], col = as.factor(restaurants$Location))

#plot(df_auto[,names(df_auto[sapply(df_auto,class) != "factor"])])

ggplot(df_auto %>% filter(veh_value <= 7,
                          claimcst0 <= 10000), aes(x=veh_value, y= claimcst0))+
  geom_point(aes(colour = gender)) +
  xlab("Vehicle value in $10,000 units") +
  ylab("Claim Size") +
  ggtitle("Vehicle Insurance Data Scatterplot") +
  theme(plot.title = element_text(hjust = .5))


lapply(c("veh_body","veh_age", "area","agecat"),function(i){
  ggplot(df_auto %>% filter(veh_value <= 7,
                          claimcst0 <= 10000), aes(x=veh_value, y= claimcst0))+
  geom_point(aes(colour = get(i))) +
  facet_wrap(. ~ get(i)) +
  xlab("Vehicle value in $10,000 units") +
  ylab("Claim Size") +
  ggtitle("Vehicle Insurance Data Scatterplot") +
  theme(plot.title = element_text(hjust = .5)) +
  guides(color=guide_legend(i))
})


ggplot(df_auto %>% mutate(log_veh_value = log(veh_value)),
       aes(x=fct_reorder(clm,log_veh_value),y=log_veh_value)) +
  geom_boxplot() +
  xlab("Occurrence of claim") +
  ylab("Log Vehicle value") +
  ggtitle("Box Plot: Claim Occurrence vs Log Vehicle value") +
  theme(plot.title = element_text(hjust = .5))


lapply(c("veh_body","veh_age", "area","agecat","gender","veh_band"),function(i){
ggplot(df_auto %>% mutate(log_claim = log(claimcst0)),
       aes(x=fct_reorder(factor(get(i)),log_claim),y=log_claim)) +
  geom_boxplot() +
  xlab(i) +
  ylab("Log Claim Amount") +
  ggtitle(paste0("Box Plot: ", toupper(i)," vs Log claim") ) +
  theme(plot.title = element_text(hjust = .5))

})


ggplot(df_auto %>% filter(claimcst0 <= 15000) %>% 
         mutate(clm_size = claimcst0/1000), aes(x=clm_size)) +
  geom_histogram(binwidth = .245) +
  xlab("Claim size ($1000s)") +
  ggtitle("Vehicle damage claims") +
  theme(plot.title = element_text(hjust = .5)) +
  scale_x_continuous(limits = c(.2, 15)) +
  ylim(0,800)

lapply(c("veh_body","veh_age", "area","agecat","gender","veh_band"),function(i){
ggplot(df_auto, aes(x= clm,  group=get(i))) + 
 geom_bar(aes(y = ..prop.., fill = factor(..x..,labels = c("0","1"))), stat="count") +
 geom_text(aes(label = scales::percent(..prop..),
                   y= ..prop.. ), stat= "count", 
           vjust = .10, size = 2.5)+
 labs(y = "Percent", fill="Claim Occurrence") +
 facet_wrap(get(i)~.) +
 coord_cartesian(ylim = c(0,1)) +    
 scale_y_continuous(labels = scales::percent) +
 ggtitle(paste0("Occurrence of Claim Versus ",toupper(i))) +
 theme(plot.title = element_text(hjust = .5)) 

})


```

```{r, summary}

cor(df_auto[df_auto$claimcst0 !=0,c("veh_value","exposure","numclaims",
                                    "claimcst0","veh_age")])


lapply(c("veh_body","veh_age", "area","agecat","gender","veh_band"),function(i){
df_auto_smry <- df_auto %>% 
  group_by(get(i)) %>% 
  summarise(exposure=sum(exposure,na.rm = T),
            num_clm = sum(numclaims,na.rm =T),
            clm_amt = sum(claimcst0,na.rm = T)) %>% 
  mutate(freq = num_clm/exposure,
         severity = clm_amt/num_clm,
         pure_prem = clm_amt/exposure) %>% 
  rename(!!i := "get(i)") %>% 
  mutate(base_level = unique(get(i))[which.max(exposure)])  

})  

## Change the factor base level to the level which has the most exposure

var_list <- c("veh_body","veh_age", "area","agecat","gender","veh_band")

base_list <- c("SEDAN","3","C","4","F","<=25") 

for(i in 1:length(var_list)){
  
   df_auto[,var_list[i]] <- relevel(factor(df_auto[,var_list[i]]), 
                                   ref = base_list[i])
}

##optimal cutoff

searchgrid <- seq(.01,.99,.01)
result <- cbind(searchgrid,NA)

cost2 <- function(r,pi){
  weight1 = 7
  weight0 = 1
  c1= (r==1) & (pi < pcut)
  c0=  (r==0) & (pi > pcut)
  return(mean(weight1*c1 + weight0*c0))
}

for(i in 1:length(searchgrid)){
  pcut <- result[i,1]
  result[i,2] <- cost2(df_auto$clm, predict(model_step_aic, type = "response"))
}

plot(result)

searchgrid[which(result[,2] == min(result[,2]))]
```

```{r}
source("logit_exposure_adjusted.r")

model_0 = glm(clm ~ agecat + area + gender + veh_age + veh_body + veh_value,
              family=binomial(link=logitexp(exposure=df_auto$exposure)),
              data=df_auto)
model_null <- glm(clm ~ 1,
              family=binomial(link=logitexp(exposure=df_auto$exposure)),
              data=df_auto)

#stepwise AIC

model_step_aic <- step(model_null, scope=list(model_null, upper=model_0),
                       k=2,direction = "forward")

model_final <- glm(clm ~ agecat + veh_age + veh_body + area + veh_value,
                  family=binomial(link=logitexp(exposure=df_auto$exposure)),
                  data=df_auto)
```

```{r, confusion_matrix, warning=FALSE}

source("ROC_function.r")

cutoff=.14

model_0_insample <- predict(model_0,type = "response")
model_0_insample <- model_0_insample > cutoff
model_0_insample <- as.numeric(model_0_insample)

tbl_cm <- table(df_auto$clm, model_0_insample, dnn = c("Actual","Predicted"))

roc_0 <- roc(clm ~ model_0_insample, data=df_auto)
auc <- round(as.numeric(roc_0$auc),3)

ROC(model_0_insample,df_auto$clm,auc,cutoff)


df_cm <- as.data.frame(tbl_cm,row.names = c(1,2,3,4)) %>%
  mutate(Actual = ifelse(Actual == 0,"No","Yes"),
         Predicted = ifelse(Predicted == 0,"No","Yes")) %>% 
  pivot_wider(names_from = "Predicted",values_from = "Freq") %>%
  rowwise() %>%
  mutate(Total = sum(No,Yes,na.rm = T))
  
df_total <- as.data.frame(t(sapply(df_cm[,-1],sum)))
df_total$Actual <- c("Total")

df_cm <- rbind(df_cm,df_total)

cbind(name =rownames(df_cm),df_cm) %>%
   mutate(name = ifelse(name == 2,"Actual Claim","")) %>% 
   kbl(format = "html",format.args = list(big.mark = ","),
    caption = paste0("<center>Classification table with ",
                     cutoff," threshold</center>"),
    col.names = c("","","No","Yes","Total")) %>%
  add_header_above(c(" "," ","Predicted Claim" = 3)) %>% 
  collapse_rows(1, valign = "top") %>% 
  column_spec(1:4, width = "6em") %>% 
  column_spec(1,extra_css = 'vertical-align: middle !important;') %>% 
  kable_styling(full_width = F, html_font = "Cambria")
```



